# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        coq_version:
          - '8.11'
          - dev
        ocaml_version: ['4.07-flambda']
      fail-fast: false  # don't stop jobs if one fails

    steps:
      - uses: actions/checkout@v3

      - name: Docker-Coq Action
        uses: coq-community/docker-coq-action@v1.2.4
        with:
          opam_file: 'folder/coq-proj.opam'
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
      - name: Build prop_logic
        run: make -C prop_logic
